name: Style Checker

on: [pull_request]

jobs:
  black:
    name: Python Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
